version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/src/app
      - "./data:/usr/src/app/data"
    environment:
      - FLASK_APP=__init__.py
      - FLASK_ENV=development  # Set to development to disable caching of templates and static files
      - SECRET_KEY=${SECRET_KEY}
    command: gunicorn -w 4 -b 0.0.0.0:5001 __init__:app
